[package]
name = "rscheme"
version = "0.1.0"
authors = ["Ryo Higasigawa <ryo.higasigawa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "7.1.0"
